backup:
  prefix:
  cron-schedule:
  auto-create-bucket:
  pg-dump-exe-path: /usr/bin/pg_dump

s3:
  access-key:
  secret-key:
  bucket-name:
  bucket-path:
  endpoint-url:

db:
  user:
  password:
  name:
  host:
  port:

---
spring.profiles: test
backup:
  prefix: backup
  cron-schedule: "*/10 * * * * *"
  auto-create-bucket: false
  pg-dump-exe-path: ./some-exe-file

s3:
  access-key: "myAccessKey"
  secret-key: "mySecretKey"
  bucket-name: "my_backups"
  bucket-path: "my-bucket-path/data"
  endpoint-url: "https://example.org"

db:
  user: "postgres"
  password: "password"
  name: "mydb"
  host: "localhost"
  port: 5432

